music.background=audio/music/background_loop.wav

weapon.playerFire=audio/weapon/player_fire.wav
weapon.machineGun=audio/weapon/heavy_machine_gun.wav
weapon.rocket=audio/weapon/rocket_launcher.wav
weapon.grenadeThrow=audio/weapon/grenade.wav
weapon.grenadeExplosion=audio/boss/boss_activation.wav
weapon.melee=audio/weapon/knife.wav

stage.level1Start=audio/stage/mission_1_start.wav
stage.level2Start=audio/stage/mission_2_start.wav
stage.missionComplete=audio/stage/mission_complete.wav
stage.gameOver=audio/stage/mission_all_over.wav
boss.activation=audio/boss/boss_activation.wav

voice.playerHurt=audio/voice/player_hurt.wav
voice.playerDeath=audio/voice/player_death.wav
voice.hostageThanks=audio/voice/thank_you.wav
enemy.death=audio/enemy/enemy_death.wav
movement.footstep=audio/movement/footstep.wav
