# 窗体配置
window.width=900
window.height=600
window.title=合金弹头
window.resizable=false

# 游戏配置
game.sleep=20
game.level=1
game.logicInterval=50
game.repaintInterval=20

# 玩家配置
player.speed=4
player.jumpSpeed=10
player.gravity=1
player.groundY=500