play=cn.edu.scnu.element.Play
map=cn.edu.scnu.element.MapObj
rifleman=cn.edu.scnu.element.enemy.RiflemanEnemy
bazooka=cn.edu.scnu.element.enemy.BazookaEnemy
knife=cn.edu.scnu.element.enemy.KnifeEnemy
grenadier=cn.edu.scnu.element.enemy.GrenadierEnemy
heavyGunner=cn.edu.scnu.element.enemy.HeavyGunnerEnemy
biker=cn.edu.scnu.element.enemy.BikerEnemy
hostage=cn.edu.scnu.element.hostage.Hostage
tankBoss=cn.edu.scnu.element.boss.TankBoss
towerBoss=cn.edu.scnu.element.boss.TowerBoss
