play=cn.edu.scnu.element.Play
map=cn.edu.scnu.element.MapObj

rifleman=cn.edu.scnu.element.enemy.RiflemanEnemy
bazooka=cn.edu.scnu.element.enemy.BazookaEnemy
biker=cn.edu.scnu.element.enemy.BikerEnemy
grenadier=cn.edu.scnu.element.enemy.GrenadierEnemy
heavyGunner=cn.edu.scnu.element.enemy.HeavyGunnerEnemy
knife=cn.edu.scnu.element.enemy.KnifeEnemy

tankBoss=cn.edu.scnu.element.boss.TankBoss
towerBoss=cn.edu.scnu.element.boss.TowerBoss

hostage=cn.edu.scnu.element.hostage.Hostage